name: beallibres
description: "Plataforma de gestió de la biblioteca de llibres del Bloc de l'Estudiantat Agermanat."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: any
  go_router: ^14.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  go_router_builder: ^2.7.1
  build_runner: ^2.4.13
  build_verify: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/book-cover-placeholder.png
