name: beallibres
description: "Plataforma de gestió de la biblioteca de llibres del Bloc de l'Estudiantat Agermanat."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^5.4.0
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  formz: ^0.8.0
  gap: ^3.0.1
  go_router: ^15.1.2
  intl: any
  json_annotation: ^4.9.0
  nested: ^1.0.0
  optional: ^6.1.0+1
  syncfusion_flutter_datagrid: ^29.2.4

dev_dependencies:
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  flutter_driver:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/book-cover-placeholder.png
